### ISSUE TITLE
 ARM version for Single Board Computers (Pi etc.)

### ISSUE THREAD

**Issue by GreenLunar** [markusfisch/PieDock#18]
When attempting to install on ArchLinuxARM from AUR https://aur.archlinux.org/packages/piedock/ I get a message that the software is not available for the 'armv7h' architecture.

**Comment by GreenLunar** [comment]
When attempting to install on ArchLinuxARM from AUR https://aur.archlinux.org/packages/piedock/ I get a message that the software is not available for the 'armv7h' architecture.

**Comment by markusfisch** [comment]
Hm, that's interesting 🤔 Frankly, I don't know why you're getting this message because PieDock does in fact compile on armv7. You could verify it's working by building it manually. Just clone this repo, change into the directory and run:
```
$ sh/deploy
```

I didn't compile the package for AUR, and I don't have Arch installed on armv7 so I don't know what's going wrong unfortunately 😬

**Comment by GreenLunar** [comment]
I'll refer to Arch Linux ARM forum and get back to you. Thanks
